### ISSUE TITLE
USB_ISR function

### ISSUE THREAD

**Issue by MainWire** [wagiminator/CH552-USB-NRF#1]
Hi,

I am making a project that uses the NRF24 and the CH552G. I found you'r project that looks pretty good.
I am currently trying to compile it and test it with my NRF emmiter, but I have a few problems with the compilation, first of all the USB_ISR function isn't recognized, and causes an error. 

```
void USB_ISR(void) __interrupt(INT_NO_USB) {
  USB_interrupt();
}
```

I have other compilation errors that I pasted here : https://dpaste.org/zbfYO, I suppose I missed something, because I shouldn't be having so much errors ?

The code is in a C file, I'm using platformIO to compile everything. I have literally downloaded every h file, but I still get errors.

Thanks for your help !

**Comment by wagiminator** [comment]
Unfortunately, I'm not familiar with PlatformIO. In your path I see a CH559. Please make sure that the header file ch554.h is used. Try renaming nrf2cdc.c to main.c.

**Comment by MainWire** [comment]
I finally managed to get it to compile, I just deleted everything and started over, must have done something with the files I downloaded. Thanks !
